version: "3"

services:
  deeplearning:
    build: ./
    image: deeplearning
    container_name: deeplearning
    tty: true
    volumes:
      - ./files:/files
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      DISPLAY: unix$DISPLAY
    working_dir: /files
